# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MAC0214 Atividade Curricular em Cultura e Extensão 
email: nathan@vieiraproenca.com
description: > # this means to ignore newlines until "baseurl:"
  Documentando trabalho em treinos de programação competitiva para
  a matéria MAC0214 - Atividade Curricular em Cultura e Extensão, do
  Departamento de Computação do Instituto de Matemática e Estatística.
baseurl: "/mac0214" # the subpath of your site, e.g. /blog
url: "http://nathanpro.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: nathanPro

# Build settings
markdown: kramdown
